Vagrant.configure("2") do |config|
  config.vm.box = "shekeriev/debian-11"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.vm.network "private_network", ip: "192.168.99.101"
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.provision "shell", path: "install_docker_debian.sh"
  config.vm.provision "shell", path: "containers.sh"
end